version: '3'
services:
  master:
    image: redis:5.0.3-alpine
    restart: always
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./master/redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      - redis-net

  slave_1:
    image: redis:5.0.3-alpine
    restart: always
    command: redis-server /usr/local/etc/redis/redis.conf --slaveof redis-master 6379
    volumes:
      - ./slave/redis.conf:/usr/local/etc/redis/redis.conf
    links:
      - master:redis-master
    networks:
      - redis-net
  
  slave_2:
    image: redis:5.0.3-alpine
    restart: always
    command: redis-server /usr/local/etc/redis/redis.conf --slaveof redis-master 6379
    volumes:
      - ./slave/redis.conf:/usr/local/etc/redis/redis.conf
    links:
      - master:redis-master
    networks:
      - redis-net

  slave_3:
    image: redis:5.0.3-alpine
    restart: always
    command: redis-server /usr/local/etc/redis/redis.conf --slaveof redis-master 6379
    volumes:
      - ./slave/redis.conf:/usr/local/etc/redis/redis.conf
    links:
      - master:redis-master
    networks:
      - redis-net

  slave_4:
    image: redis:5.0.3-alpine
    restart: always
    command: redis-server /usr/local/etc/redis/redis.conf --slaveof redis-master 6379
    volumes:
      - ./slave/redis.conf:/usr/local/etc/redis/redis.conf
    links:
      - master:redis-master
    networks:
      - redis-net

  sentinel:
    build: sentinel
    restart: always
    environment:
      - SENTINEL_DOWN_AFTER=5000
      - SENTINEL_FAILOVER=5000
      - SENTINEL_QUORUM=2
    links:
      - master:redis-master
    depends_on:
      - master
      - slave_1
      - slave_2
      - slave_3
      - slave_4
    networks:
      - redis-net
  
  haproxy:
    build: haproxy
    restart: always
    ports:
      - '9000:9000'
      - '6379:6379'
    environment:
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=admin
      - REDIS_HOSTS=master,slave_1,slave_2,slave_3,slave_4
    depends_on:
      - master
      - slave_1
      - slave_2
      - slave_3
      - slave_4
      - sentinel
    networks:
      - redis-net
      - backend-net

networks:
  redis-net:
    driver: bridge
  backend-net:
    external:
      name: donz-app-backend_umbala